
services:
  willsmith:
    # Currently, there is only a beta version.
    image: zsio/willsmith:v0.0.1-beta.4
    container_name: willsmith
    restart: unless-stopped
    environment:
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - 3000:3000
