import type { Metadata } from "next";
import {
  TooltipProvider,
} from "@/components/ui/tooltip"

import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TooltipProvider>
      <body>{children}</body>
      </TooltipProvider>
    </html>
  );
}
